#!/bin/bash

name=$(jq -r ".name" data.json)
height=$(jq -r ".height" data.json)
weight=$(jq -r ".weight" data.json)
type=$(jq -r ".types[0] | .type.name" data.json)

formatted_height=$(awk "BEGIN {print $height / 10}")
formatted_weight=$(awk "BEGIN {print $weight / 10}")

echo "Pikachu is of type Electric, weighs 6kg, and is 0.4m tall." | sed -e s/Pikachu/$name/ -e s/Electric/$type/ -e  s/6kg/${formatted_weight}kg/ -e s/0.4m/${formatted_height}m/